# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170827_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sale_off',
            field=models.FloatField(default=None),
        ),
    ]
